In [1]:
%load_ext autoreload
%autoreload 1
%aimport numpy2stl

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import numpy2stl as np2stl

%load_ext line_profiler
%matplotlib

Using matplotlib backend: Qt5Agg


## Generation facets from a random array 

In [21]:
mat = np.random.randint(20, high=30,  size=(10,10))
mat[2:6,2:6] = -1

mat[7:10,2:7] = 20
#mat[:,8] = np.linspace(10, 25, num=10, endpoint=True)
#mat[:,9] = np.linspace(10, 25, num=10, endpoint=True)

facets= np2stl.numpy2stl(mat, solid=True, mask_val= 0)
vertices = np.array([[facet[3:6],facet[6:9],facet[9:12]] for facet in facets])

print(mat)

Creating top...
Creating Edges...
Creating bottom...
[[21 23 24 29 23 29 26 21 25 27]
 [25 25 21 22 21 26 29 25 23 26]
 [23 28 -1 -1 -1 -1 22 24 27 23]
 [28 24 -1 -1 -1 -1 23 24 21 27]
 [28 27 -1 -1 -1 -1 28 26 25 28]
 [29 23 -1 -1 -1 -1 24 21 23 28]
 [26 29 27 21 21 26 21 21 23 27]
 [22 27 20 20 20 20 20 27 25 27]
 [29 26 20 20 20 20 20 26 24 27]
 [25 21 20 20 20 20 20 25 27 23]]


## View 3D object

In [4]:
np2stl.draw_3D_vertices(vertices)

## Identify and Color each Surface

In [15]:
normals = np2stl.calculate_normals(vertices)
surfaces = np2stl.get_surfaces(vertices)
surf_color = np.array([np.abs(normals[surf[0]]) for surf in surfaces])
np2stl.draw_3D_vertices(vertices, surfaces=surfaces, surf_color=surf_color)

## Simplify 3D Object and View it 

In [22]:
vertices_out = np2stl.simplify_object_3D(vertices)
normals = np2stl.calculate_normals(vertices_out)
surfaces = np2stl.get_surfaces(vertices_out)
surf_color = np.array([np.abs(normals[surf[0]]) for surf in surfaces])
np2stl.draw_3D_vertices(vertices_out, surfaces=surfaces, surf_color=surf_color )

Open edges exist in object


In [7]:
plt.close('all')

surfaces = np2stl.get_surfaces(vertices)
normals = np2stl.calculate_normals(vertices)

for i in [-2]:
    surf = surfaces[i]
    normal = normals[surf][0]
    vert_test = vertices[surf]  
    
    edges = np2stl.get_open_edges(vert_test)
    perimeters = np2stl.get_ordered_perimeter(edges)
    perimeter_2d = [np2stl.rotate_3D(peri, normal, [0,0,1] ) for peri in perimeters ]
    [plt.plot(p[:,0],p[:,1]) for p in perimeter_2d]
    plt.figure()
    peri_out = np2stl.partition_concave(perimeter_2d)
    [plt.plot(p[:,0],p[:,1]) for p in peri_out]

In [39]:
plt.close('all')

surfaces = np2stl.get_surfaces(vertices)
normals = np2stl.calculate_normals(vertices)

for i in [-2]:
    surf = surfaces[i]
    normal = normals[surf][0]
    vert_test = vertices[surf]  
    
    edges = np2stl.get_open_edges(vert_test)
    perimeters = np2stl.get_ordered_perimeter(edges)

    ## Flatten boundry to 2D
    perimeter_2d = [np2stl.rotate_3D(peri, normal, [0,0,1] ) for peri in perimeters ]
    points_2d_flat = np2stl.np.concatenate(perimeter_2d)
    
    ## Simplify Triangulation 
    vert_2D_tri = np2stl.triangulate_polygon(perimeter_2d)
    np2stl.draw_3D_vertices(vert_test)
    np2stl.draw_3D_vertices(vert_2D_tri)

In [17]:
vert_2D_tri

array([[[ 0.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 1., -1.,  0.]],

       [[ 0.,  0.,  0.],
        [ 1., -1.,  0.],
        [ 1.,  0.,  0.]],

       [[ 1.,  0.,  0.],
        [ 1., -1.,  0.],
        [ 2., -1.,  0.]],

       [[ 1.,  0.,  0.],
        [ 2., -1.,  0.],
        [ 2.,  0.,  0.]],

       [[ 2.,  0.,  0.],
        [ 2., -1.,  0.],
        [ 3., -1.,  0.]],

       [[ 2.,  0.,  0.],
        [ 3., -1.,  0.],
        [ 3.,  0.,  0.]],

       [[ 3.,  0.,  0.],
        [ 3., -1.,  0.],
        [ 4., -1.,  0.]],

       [[ 3.,  0.,  0.],
        [ 4., -1.,  0.],
        [ 4.,  0.,  0.]],

       [[ 4.,  0.,  0.],
        [ 4., -1.,  0.],
        [ 5., -1.,  0.]],

       [[ 4.,  0.,  0.],
        [ 5., -1.,  0.],
        [ 5.,  0.,  0.]],

       [[ 5.,  0.,  0.],
        [ 5., -1.,  0.],
        [ 6., -1.,  0.]],

       [[ 5.,  0.,  0.],
        [ 6., -1.,  0.],
        [ 6.,  0.,  0.]],

       [[ 6.,  0.,  0.],
        [ 6., -1.,  0.],
        [ 7.,  0.,  0.]],


In [1138]:
peri_out = np2stl.partition_concave(perimeter_2d)
[plt.plot(p[:,0],p[:,1]) for p in peri_out[::-1]]

[[<matplotlib.lines.Line2D at 0x1dfd0199fc8>],

In [1127]:
p = perimeter_2d[0]
edges = np.array(list(zip(p, np.roll(p,1,axis=0) )))
edges

array([[[ 0.,  0.,  0.],
        [ 1.,  0.,  0.]],

       [[ 0., -1.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0., -2.,  0.],
        [ 0., -1.,  0.]],

       [[ 0., -3.,  0.],
        [ 0., -2.,  0.]],

       [[ 0., -4.,  0.],
        [ 0., -3.,  0.]],

       [[ 0., -5.,  0.],
        [ 0., -4.,  0.]],

       [[ 0., -6.,  0.],
        [ 0., -5.,  0.]],

       [[ 0., -7.,  0.],
        [ 0., -6.,  0.]],

       [[ 0., -8.,  0.],
        [ 0., -7.,  0.]],

       [[ 0., -9.,  0.],
        [ 0., -8.,  0.]],

       [[ 1., -9.,  0.],
        [ 0., -9.,  0.]],

       [[ 2., -9.,  0.],
        [ 1., -9.,  0.]],

       [[ 3., -9.,  0.],
        [ 2., -9.,  0.]],

       [[ 4., -9.,  0.],
        [ 3., -9.,  0.]],

       [[ 5., -9.,  0.],
        [ 4., -9.,  0.]],

       [[ 6., -9.,  0.],
        [ 5., -9.,  0.]],

       [[ 7., -9.,  0.],
        [ 6., -9.,  0.]],

       [[ 8., -9.,  0.],
        [ 7., -9.,  0.]],

       [[ 9., -9.,  0.],
        [ 8., -9.,  0.]],

       [[ 9.

[array([[0., 0., 0.],
        [0., 1., 0.],
        [0., 2., 0.],
        [0., 3., 0.],
        [0., 4., 0.],
        [0., 5., 0.],
        [0., 6., 0.],
        [0., 7., 0.],
        [0., 8., 0.],
        [0., 9., 0.],
        [1., 9., 0.],
        [2., 9., 0.],
        [3., 9., 0.],
        [4., 9., 0.],
        [5., 9., 0.],
        [6., 9., 0.],
        [7., 9., 0.],
        [8., 9., 0.],
        [9., 9., 0.],
        [9., 8., 0.],
        [9., 7., 0.],
        [9., 6., 0.],
        [9., 5., 0.],
        [9., 4., 0.],
        [9., 3., 0.],
        [9., 2., 0.],
        [9., 1., 0.],
        [9., 0., 0.],
        [8., 0., 0.],
        [7., 0., 0.],
        [6., 0., 0.],
        [5., 0., 0.],
        [4., 0., 0.],
        [3., 0., 0.],
        [2., 0., 0.],
        [1., 0., 0.]]), array([[1., 2., 0.],
        [1., 1., 0.],
        [2., 1., 0.],
        [3., 1., 0.],
        [4., 1., 0.],
        [5., 1., 0.],
        [6., 1., 0.],
        [6., 2., 0.],
        [6., 3., 0.],
        [

In [211]:
plt.close('all')

## Evaluate tool preformance

In [7]:
%lprun -f np2stl.numpy2stl np2stl.numpy2stl(mat, solid=True, mask_val= 0)

Creating top...
Creating Edges...
Creating bottom...


In [54]:
%lprun -f np2stl.simplify_surface np2stl.simplify_object_3D(vertices)

## Use for editing modules

In [750]:
%debug np2stl.simplify_object_3D(vertices)